### ISSUE TITLE
Only record idempotent requests when the response code is 2XX

### ISSUE THREAD

**Issue by ryanwjackson** [LedgerSync/rails_app#24]
**Is your feature request related to a problem? Please describe.**
It becomes difficult to retry requests when recording failures and those are returned with the same idempotency key.

**Describe the solution you'd like**
Change the behavior to only record 2XX responses.

**Describe alternatives you've considered**
- Require the API user to create a new idempotency key if the previous request fails.

**Comment by ryanwjackson** [comment]
@mattgmarcus Just want to confirm this is what you were thinking.  Also, I am not quite sure what would be considered "standard" here as far as this vs. the listed alternative.  I believe we went the alternative root at the previous project, but the idea was that you could easily use IDs in your system (assuming globally unique) as idempotency keys.  Of course that would have failed for the same reasons mentioned above that if anything but a 401 was returned it would continue to return.

Just as reference:

[**Stripe**](https://stripe.com/docs/api/idempotent_requests)

> Stripe's idempotency works by saving the resulting status code and body of the first request made for any given idempotency key, regardless of whether it succeeded or failed. Subsequent requests with the same key return the same result, including 500 errors.

I suppose I personally lean more towards the current implementation in that it seems more "correct."  

Thoughts?

**Comment by mattgmarcus** [comment]
The Stripe API docs also say
```
Results are only saved if an API endpoint started executing. If incoming parameters failed validation, or the request conflicted with another that was executing concurrently, no idempotent result is saved because no API endpoint began execution. It is safe to retry these requests.
```
which makes sense. Essentially, you'd save the idempotency key if some operation could have happened, since you want to ensure it doesn't happen more than once. 

As things are written right now in LedgerSync, I often hit the validation errors when testing the API, and then I have to open a rails console to delete the idempotency key record, which is a lot of work. Also this would make it hard to retry jobs that hit L.S.

I would prefer what I suggested
