### ISSUE TITLE
Change automatic redirects in auth token controller

### ISSUE THREAD

**Issue by mattgmarcus** [LedgerSync/rails_app#37]
Should we still automatically do this redirect for the `show` action https://github.com/LedgerSync/rails_app/blob/master/app/controllers/auth_tokens_controller.rb#L2

The reason I ask is that we now support redirects within the show action, so this would short circuit that

Alternatively, we could change this method
```  
def redirect_if_logged_in
    return if current_user.blank?

    flash[:info] = t('authorization.already_logged_in')
    redirect_to root_url
  end
```

to be 
```
  def redirect_if_logged_in
    return if current_user.blank?
   
    if redirect?
      redirect_to pop_redirect_url
    else
      flash[:info] = t('authorization.already_logged_in')
      redirect_to root_url
    end
  end
```

**Comment by ryanwjackson** [comment]
Interesting.  I thought we had tests for this, but maybe only for the `auth_token` part (https://github.com/LedgerSync/rails_app/blob/master/spec/features/authentication_spec.rb#L37).  We should write a test for this too.

But yes, I agree, we need to change the logic there.  If you get to it (even writing a test), lmk.  Otherwise, assign to me and I'll tackle it.

**Comment by mattgmarcus** [comment]
I'm going to assign to you
